/**
 * Hand-authored mirror of the frozen wire contract.
 *
 * SOURCE OF TRUTH: `contracts/openapi.yaml` and
 * `contracts/websocket-envelopes.schema.json`. The canonical TypeScript for the
 * REST surface is GENERATED by `pnpm gen:api` into `src/api/generated/schema.ts`
 * (gitignored). These hand-authored types exist so the app type-checks BEFORE
 * `gen:api` has been run (the generated dir is not committed). When the two
 * disagree, the generated output — i.e. the contract — wins; update this file or
 * (better) re-export from the generated types.
 */

// --- REST: GET /health (HealthStatus) ---
export interface HealthStatus {
  status: 'ok';
  service: string;
  version: string;
}

// --- REST: GET /health/ready (ReadinessStatus) ---
export type ReadinessState = 'ready' | 'degraded';

export interface DependencyStatus {
  /** Dependency identifier (e.g. postgres, redis, minio). */
  name: string;
  ok: boolean;
  /** Optional human-readable detail when not ok. */
  detail?: string;
}

export interface ReadinessStatus {
  status: ReadinessState;
  dependencies: DependencyStatus[];
}

// --- Auth (contracts/openapi.yaml §auth, spec 0004 §2.3) ---

/** POST /auth/login body. `password` is write-only on the wire. */
export interface LoginRequest {
  email: string;
  password: string;
}

/** 200 from POST /auth/login and POST /auth/refresh. */
export interface TokenResponse {
  /** Short-lived JWT bearer token. */
  access_token: string;
  token_type: 'bearer';
  /** Access-token lifetime in seconds. */
  expires_in: number;
}

/** Tenant roles (MVP RBAC, spec 0004 §2.3). */
export type UserRole = 'member' | 'admin' | 'security';

/** 200 from GET /auth/me — the authenticated principal. */
export interface CurrentUser {
  id: string;
  email: string;
  /** Resolved from the bearer token; clients never send it (spec 0004). */
  tenant_id: string;
  roles: UserRole[];
  created_at: string;
}

// --- Collections (contracts/openapi.yaml §collections) ---

/** POST /collections body. */
export interface CollectionCreate {
  name: string;
  description?: string;
}

/** PATCH /collections/{id} body — at least one property required (minProperties: 1). */
export interface CollectionUpdate {
  name?: string;
  description?: string;
}

/** A collection (folder grouping documents). */
export interface Collection {
  id: string;
  name: string;
  description?: string;
  owner_id: string;
  document_count: number;
  created_at: string;
  updated_at: string;
}

/** 200 from GET /collections — a cursor page of collections. */
export interface CollectionList {
  items: Collection[];
  /** Cursor for the next page, or null when exhausted. */
  next_cursor?: string | null;
}

// --- Documents (contracts/openapi.yaml §documents) ---

/** Ingestion lifecycle (parse → chunk → embed). */
export type DocumentStatus = 'pending' | 'processing' | 'ready' | 'failed';

/** A document's metadata, including its ingestion status. */
export interface Document {
  id: string;
  filename: string;
  mime_type: string;
  size_bytes: number;
  collection_id: string;
  owner_id: string;
  status: DocumentStatus;
  /** Failure reason when status is failed. */
  error?: string;
  /** Number of indexed chunks (0 until ingestion completes). */
  chunk_count: number;
  created_at: string;
  updated_at: string;
}

/** 200 from GET /documents — a cursor page of documents. */
export interface DocumentList {
  items: Document[];
  next_cursor?: string | null;
}

/** Query filters for GET /documents (collection / status / filename substring). */
export interface DocumentListQuery {
  collection_id?: string;
  status?: DocumentStatus;
  /** Filename substring (lexical, not semantic). */
  q?: string;
  cursor?: string;
  limit?: number;
}

// --- Shared error model: Problem (RFC-9457 application/problem+json) ---
export interface ProblemFieldError {
  field: string;
  message: string;
}

export interface Problem {
  /** URI identifying the problem type. Defaults to "about:blank". */
  type: string;
  /** Short, human-readable summary. */
  title: string;
  /** HTTP status code. */
  status: number;
  /** Human-readable explanation for this occurrence. */
  detail?: string;
  instance?: string;
  /** Stable, machine-readable error code for clients to branch on. */
  code?: string;
  /** Field-level validation errors, when applicable. */
  errors?: ProblemFieldError[];
}

// --- Chat (contracts/openapi.yaml §chat) ---

/** Picker grouping for chat models. */
export type ModelTier = 'frontier' | 'fast' | 'oss';

/** GET /models item — one selectable chat model. */
export interface ChatModelInfo {
  /** Model id passed to chat (e.g. anthropic/claude-opus-4.8). */
  id: string;
  /** Display name for the picker. */
  label: string;
  /** e.g. anthropic, openai, google, deepseek, qwen. */
  provider: string;
  tier: ModelTier;
  is_default: boolean;
  description?: string;
}

/** 200 from GET /models. */
export interface ModelList {
  items: ChatModelInfo[];
}

export type MessageRole = 'user' | 'assistant' | 'system';

/**
 * A clickable, passage-level reference (spec 0004 INV-3). Resolves to a document
 * the caller is permitted to see and a character span within it.
 */
export interface Citation {
  id: string;
  document_id: string;
  document_name: string;
  chunk_id: string;
  /** The cited passage text. */
  snippet: string;
  char_start: number;
  char_end: number;
  /** Optional retrieval/rerank score. */
  score?: number;
}

export interface Message {
  id: string;
  session_id: string;
  role: MessageRole;
  content: string;
  /** Model that produced an assistant message (absent for user). */
  model?: string;
  /** Passage-level citations (assistant messages only). */
  citations?: Citation[];
  created_at: string;
}

export interface MessageList {
  items: Message[];
  next_cursor?: string | null;
}

export interface ChatSession {
  id: string;
  title: string;
  /** The session's default model id. */
  model: string;
  owner_id: string;
  message_count: number;
  created_at: string;
  updated_at: string;
}

export interface ChatSessionList {
  items: ChatSession[];
  next_cursor?: string | null;
}

/** POST /chat/sessions body. */
export interface ChatSessionCreate {
  title?: string;
  /** A model id from GET /models; omitted = server default. */
  model?: string;
}

/** PATCH /chat/sessions/{id} body — at least one property. */
export interface ChatSessionUpdate {
  title?: string;
  model?: string;
}

/** POST /chat/sessions/{id}/messages body. */
export interface SendMessageRequest {
  content: string;
  /** Override the session model for this turn (a GET /models id). */
  model?: string;
  /** Restrict retrieval to these collections; omitted = all permitted docs. */
  collection_ids?: string[];
}

/** 202 from POST /chat/sessions/{id}/messages. */
export interface SendMessageResponse {
  /** The persisted user message. */
  message: Message;
  /** Subscribe to this WebSocket stream id for the assistant answer. */
  stream_id: string;
}

// --- WebSocket envelopes (contracts/websocket-envelopes.schema.json) ---
// Lifecycle: start -> (delta | event)* -> done | error, exactly one terminal.
export type EnvelopeType = 'start' | 'delta' | 'event' | 'done' | 'error';

interface BaseEnvelope {
  type: EnvelopeType;
  /** Correlates all messages of one logical stream. */
  streamId: string;
  /** Monotonically increasing per streamId; defines ordering. */
  seq: number;
  /** Server send time (optional, ISO-8601). */
  ts?: string;
}

export interface StartEnvelope extends BaseEnvelope {
  type: 'start';
  /** Stream-open metadata; shape defined per feature. */
  data?: Record<string, unknown>;
}

export interface DeltaEnvelope extends BaseEnvelope {
  type: 'delta';
  /** Incremental output (e.g. a token chunk). Payload shape defined per feature. */
  data: unknown;
}

export interface EventEnvelope extends BaseEnvelope {
  type: 'event';
  /** Structured side-band event name (e.g. citation, tool_call). */
  name: string;
  data?: unknown;
}

export interface DoneEnvelope extends BaseEnvelope {
  type: 'done';
  /** Terminal success summary; shape defined per feature. */
  data?: Record<string, unknown>;
}

/** Subset of Problem carried on a WS error envelope (title + status required). */
export interface WsProblem {
  title: string;
  status: number;
  detail?: string;
  code?: string;
}

export interface ErrorEnvelope extends BaseEnvelope {
  type: 'error';
  problem: WsProblem;
}

export type WsEnvelope =
  | StartEnvelope
  | DeltaEnvelope
  | EventEnvelope
  | DoneEnvelope
  | ErrorEnvelope;

/** A terminal envelope ends a stream (exactly one per streamId). */
export type TerminalEnvelope = DoneEnvelope | ErrorEnvelope;

// --- Chat answer-stream payloads (websocket-envelopes.schema.json x-chatStream) ---
// These slot into the generic envelope `data`/`event` shapes for a chat answer:
//   start(ChatStartData) -> ( delta(ChatTokenDelta) | event:tool_call(ChatToolCall)
//     | event:tool_result(ChatToolResult) | event:citation(ChatCitation) )*
//   -> done(ChatDoneData) | error(Problem)

/** `start.data` for a chat answer stream. */
export interface ChatStartData {
  sessionId: string;
  /** Id the in-progress assistant message will be persisted under. */
  messageId: string;
  /** Model id producing this answer. */
  model: string;
}

/** `delta.data` — one streamed chunk of the assistant answer. */
export interface ChatTokenDelta {
  text: string;
}

/**
 * `event.data` for name=citation. Mirrors the REST Citation (spec 0004 INV-3) but
 * camelCased per the WS envelope schema. Rendered as a clickable reference
 * resolving to the document + span.
 */
export interface ChatCitation {
  id: string;
  documentId: string;
  documentName: string;
  chunkId: string;
  snippet: string;
  charStart: number;
  charEnd: number;
  score?: number;
}

/** Retrieval tool the chat agent can invoke (surfaced for "searching…" UX). */
export type ChatTool = 'search_text' | 'search_documents' | 'get_document';

/** `event.data` for name=tool_call — the agent invoked a retrieval tool. */
export interface ChatToolCall {
  callId: string;
  tool: ChatTool;
  args: Record<string, unknown>;
}

/** `event.data` for name=tool_result — outcome of a tool_call. */
export interface ChatToolResult {
  callId: string;
  tool: ChatTool;
  hitCount: number;
  summary?: string;
}

/** `done.data` — terminal success summary for a chat answer. */
export interface ChatDoneData {
  messageId: string;
  /** e.g. stop, length, content_filter. */
  finishReason: string;
  citationCount: number;
  usage?: {
    promptTokens?: number;
    completionTokens?: number;
    totalTokens?: number;
  };
}
