/**
 * Hand-authored mirror of the frozen wire contract.
 *
 * SOURCE OF TRUTH: `contracts/openapi.yaml` and
 * `contracts/websocket-envelopes.schema.json`. The canonical TypeScript for the
 * REST surface is GENERATED by `pnpm gen:api` into `src/api/generated/schema.ts`
 * (gitignored). These hand-authored types exist so the app type-checks BEFORE
 * `gen:api` has been run (the generated dir is not committed). When the two
 * disagree, the generated output — i.e. the contract — wins; update this file or
 * (better) re-export from the generated types.
 */

// --- REST: GET /health (HealthStatus) ---
export interface HealthStatus {
  status: 'ok';
  service: string;
  version: string;
}

// --- REST: GET /health/ready (ReadinessStatus) ---
export type ReadinessState = 'ready' | 'degraded';

export interface DependencyStatus {
  /** Dependency identifier (e.g. postgres, redis, minio). */
  name: string;
  ok: boolean;
  /** Optional human-readable detail when not ok. */
  detail?: string;
}

export interface ReadinessStatus {
  status: ReadinessState;
  dependencies: DependencyStatus[];
}

// --- Auth (contracts/openapi.yaml §auth, spec 0004 §2.3) ---

/** POST /auth/login body. `password` is write-only on the wire. */
export interface LoginRequest {
  email: string;
  password: string;
}

/** 200 from POST /auth/login and POST /auth/refresh. */
export interface TokenResponse {
  /** Short-lived JWT bearer token. */
  access_token: string;
  token_type: 'bearer';
  /** Access-token lifetime in seconds. */
  expires_in: number;
}

/** Tenant roles (MVP RBAC, spec 0004 §2.3). */
export type UserRole = 'member' | 'admin' | 'security';

/** 200 from GET /auth/me — the authenticated principal. */
export interface CurrentUser {
  id: string;
  email: string;
  /** Resolved from the bearer token; clients never send it (spec 0004). */
  tenant_id: string;
  roles: UserRole[];
  created_at: string;
}

// --- Collections (contracts/openapi.yaml §collections) ---

/** POST /collections body. */
export interface CollectionCreate {
  name: string;
  description?: string;
}

/** PATCH /collections/{id} body — at least one property required (minProperties: 1). */
export interface CollectionUpdate {
  name?: string;
  description?: string;
}

/** A collection (folder grouping documents). */
export interface Collection {
  id: string;
  name: string;
  description?: string;
  owner_id: string;
  document_count: number;
  created_at: string;
  updated_at: string;
}

/** 200 from GET /collections — a cursor page of collections. */
export interface CollectionList {
  items: Collection[];
  /** Cursor for the next page, or null when exhausted. */
  next_cursor?: string | null;
}

// --- Documents (contracts/openapi.yaml §documents) ---

/** Ingestion lifecycle (parse → chunk → embed). */
export type DocumentStatus = 'pending' | 'processing' | 'ready' | 'failed';

/** A document's metadata, including its ingestion status. */
export interface Document {
  id: string;
  filename: string;
  mime_type: string;
  size_bytes: number;
  collection_id: string;
  owner_id: string;
  status: DocumentStatus;
  /** Failure reason when status is failed. */
  error?: string;
  /** Number of indexed chunks (0 until ingestion completes). */
  chunk_count: number;
  created_at: string;
  updated_at: string;
}

/** 200 from GET /documents — a cursor page of documents. */
export interface DocumentList {
  items: Document[];
  next_cursor?: string | null;
}

/** Query filters for GET /documents (collection / status / filename substring). */
export interface DocumentListQuery {
  collection_id?: string;
  status?: DocumentStatus;
  /** Filename substring (lexical, not semantic). */
  q?: string;
  cursor?: string;
  limit?: number;
}

// --- Shared error model: Problem (RFC-9457 application/problem+json) ---
export interface ProblemFieldError {
  field: string;
  message: string;
}

export interface Problem {
  /** URI identifying the problem type. Defaults to "about:blank". */
  type: string;
  /** Short, human-readable summary. */
  title: string;
  /** HTTP status code. */
  status: number;
  /** Human-readable explanation for this occurrence. */
  detail?: string;
  instance?: string;
  /** Stable, machine-readable error code for clients to branch on. */
  code?: string;
  /** Field-level validation errors, when applicable. */
  errors?: ProblemFieldError[];
}

// --- Chat (contracts/openapi.yaml §chat) ---

/** Picker grouping for chat models. */
export type ModelTier = 'frontier' | 'fast' | 'oss';

/** GET /models item — one selectable chat model. */
export interface ChatModelInfo {
  /** Model id passed to chat (e.g. anthropic/claude-opus-4.8). */
  id: string;
  /** Display name for the picker. */
  label: string;
  /** e.g. anthropic, openai, google, deepseek, qwen. */
  provider: string;
  tier: ModelTier;
  is_default: boolean;
  description?: string;
}

/** 200 from GET /models. */
export interface ModelList {
  items: ChatModelInfo[];
}

export type MessageRole = 'user' | 'assistant' | 'system';

/**
 * A clickable, passage-level reference (spec 0004 INV-3). Resolves to a document
 * the caller is permitted to see and a character span within it.
 */
export interface Citation {
  id: string;
  document_id: string;
  document_name: string;
  chunk_id: string;
  /** The cited passage text. */
  snippet: string;
  char_start: number;
  char_end: number;
  /** Optional retrieval/rerank score. */
  score?: number;
}

export interface Message {
  id: string;
  session_id: string;
  role: MessageRole;
  content: string;
  /** Model that produced an assistant message (absent for user). */
  model?: string;
  /** Passage-level citations (assistant messages only). */
  citations?: Citation[];
  created_at: string;
}

export interface MessageList {
  items: Message[];
  next_cursor?: string | null;
}

export interface ChatSession {
  id: string;
  title: string;
  /** The session's default model id. */
  model: string;
  owner_id: string;
  message_count: number;
  created_at: string;
  updated_at: string;
}

export interface ChatSessionList {
  items: ChatSession[];
  next_cursor?: string | null;
}

/** POST /chat/sessions body. */
export interface ChatSessionCreate {
  title?: string;
  /** A model id from GET /models; omitted = server default. */
  model?: string;
}

/** PATCH /chat/sessions/{id} body — at least one property. */
export interface ChatSessionUpdate {
  title?: string;
  model?: string;
}

/** POST /chat/sessions/{id}/messages body. */
export interface SendMessageRequest {
  content: string;
  /** Override the session model for this turn (a GET /models id). */
  model?: string;
  /** Restrict retrieval to these collections; omitted = all permitted docs. */
  collection_ids?: string[];
}

/** 202 from POST /chat/sessions/{id}/messages. */
export interface SendMessageResponse {
  /** The persisted user message. */
  message: Message;
  /** Subscribe to this WebSocket stream id for the assistant answer. */
  stream_id: string;
}

// --- Search (contracts/openapi.yaml §search, M2 #80) ---

/** Where a result originated (`connector` reserved; framework is post-MVP). */
export type ResultSource = 'upload' | 'chat' | 'connector';

/**
 * Per-result permission outcome. Trimmed results are normally `allowed`;
 * `restricted` is metadata-only (exists, but content withheld). Passages the
 * caller may not see at all are never returned — counted in `hidden_count`
 * (spec 0004 INV-2).
 */
export type PermissionState = 'allowed' | 'restricted';

/** A character span within a snippet that matched the query (for highlighting). */
export interface MatchSpan {
  start: number;
  end: number;
}

/** One permission-trimmed ranked search result (spec 0004 INV-1/INV-2). */
export interface SearchResult {
  id: string;
  title: string;
  /** Excerpt of the matched passage. */
  snippet: string;
  /** Character spans within `snippet` that matched the query. */
  match_spans: MatchSpan[];
  /** Human-readable explanation of why this result ranked. */
  why_matched: string;
  source: ResultSource;
  /** Content type of the result (e.g. document, message). */
  type: string;
  /** Owning principal id, when known (null for system/connector content). */
  owner?: string | null;
  /** Freshness — when this result was last indexed. */
  last_indexed: string;
  permission: PermissionState;
  /** Source document id when the result resolves to a document (click-through). */
  document_id?: string;
  /** Optional retrieval/rerank score. */
  score?: number;
}

/**
 * A citation backing the direct answer — references a passage present in this
 * response's `results` (by `result_id`), so an answer can never cite a passage
 * the caller could not retrieve (spec 0004 INV-3).
 */
export interface SearchCitation {
  /** Id of the SearchResult this citation refers to. */
  result_id: string;
  /** The specific cited passage text (a substring of the result snippet). */
  snippet?: string;
  char_start?: number;
  char_end?: number;
}

/**
 * An optional synthesized answer. Present only when the permitted results
 * support it; every claim is backed by `citations` (spec 0004 INV-3).
 */
export interface DirectAnswer {
  /** The synthesized answer (rendered as sanitized markdown). */
  text: string;
  citations: SearchCitation[];
}

/** 200 from GET /search — a page of permission-trimmed ranked results. */
export interface SearchResponse {
  /** The query that produced this page (echoed back). */
  query: string;
  results: SearchResult[];
  /** Optional cited answer; omitted when nothing permitted answers the query. */
  direct_answer?: DirectAnswer;
  /**
   * How many otherwise-matching results were withheld because they are outside
   * the caller's permissions (spec 0004 INV-2).
   */
  hidden_count: number;
  next_cursor?: string | null;
}

/** Query filters for GET /search (`q` required). */
export interface SearchQuery {
  q: string;
  collection_id?: string;
  source?: ResultSource;
  /** Restrict to one content type (e.g. document, message). */
  type?: string;
  cursor?: string;
  limit?: number;
}

// --- Audit (contracts/openapi.yaml §audit, M2 #80) ---

/** Audit event taxonomy (spec 0004 §2.4). */
export type AuditEventType =
  | 'auth.login'
  | 'auth.login_failed'
  | 'auth.logout'
  | 'collection.created'
  | 'document.uploaded'
  | 'document.viewed'
  | 'document.downloaded'
  | 'document.deleted'
  | 'retrieval.query'
  | 'answer.generated'
  | 'permission.denied'
  | 'action.requested'
  | 'action.approved'
  | 'action.executed';

/** The outcome recorded for an audit event (spec 0004 §2.4). */
export type AuditDecision = 'allowed' | 'denied' | 'error';

/** Whether a retrieval candidate was allowed into the result set or excluded. */
export type AuditCandidateDisposition = 'allow' | 'exclude';

/**
 * One retrieval candidate considered for a decision, and whether it was allowed
 * or excluded — with the reason. The provenance that makes a permission/answer
 * decision reviewable (spec 0004 §2.4).
 */
export interface AuditCandidate {
  resource_id: string;
  disposition: AuditCandidateDisposition;
  /** Why it was allowed or excluded (e.g. "in allow-set", "owner mismatch"). */
  reason: string;
  score?: number;
}

/** Why a decision was made — candidate dispositions plus the raw recorded payload. */
export interface AuditProvenance {
  candidates: AuditCandidate[];
  /** The raw recorded metadata payload (model id, query hash, etc.). */
  raw?: Record<string, unknown>;
}

/** One append-only audit event (spec 0004 §2.4). */
export interface AuditEvent {
  id: string;
  /** Event time (UTC ISO-8601). */
  ts: string;
  /** The acting principal — a user id, or `system` / `anonymous`. */
  actor: string;
  tenant_id: string;
  event_type: AuditEventType;
  /** The resource the event touched, when applicable. */
  resource_id?: string | null;
  decision: AuditDecision;
  provenance: AuditProvenance;
}

/** 200 from GET /audit — a cursor page of audit events (newest → oldest). */
export interface AuditEventList {
  items: AuditEvent[];
  next_cursor?: string | null;
}

/** Query filters for GET /audit (admin / security only). */
export interface AuditQuery {
  /** One actor (user id, or `system`/`anonymous`). */
  actor?: string;
  event_type?: AuditEventType;
  resource_id?: string;
  /** Inclusive lower bound on event timestamp (UTC ISO-8601). */
  from?: string;
  /** Exclusive upper bound on event timestamp (UTC ISO-8601). */
  to?: string;
  cursor?: string;
  limit?: number;
}

// --- Admin (contracts/openapi.yaml §admin, M2 #80) ---

/** A tenant member and their role(s) for the admin roster. */
export interface Member {
  id: string;
  email: string;
  /** The member's tenant roles (MVP RBAC, spec 0004 §2.3). */
  role: UserRole[];
}

/** 200 from GET /admin/members — a cursor page of members. */
export interface MemberList {
  items: Member[];
  next_cursor?: string | null;
}

/** One allowed model and the governance tier it maps to. */
export interface ModelGovernanceEntry {
  /** A model id (e.g. anthropic/claude-opus-4.8). */
  model_id: string;
  /** The governance tier this model is approved at. */
  tier: string;
  /** Display name for the admin console. */
  label?: string;
}

/** A governance tier referenced by allowed models. */
export interface ModelGovernanceTier {
  id: string;
  description: string;
}

/** 200 from GET /admin/model-governance — read-only model governance. */
export interface ModelGovernance {
  allowed_models: ModelGovernanceEntry[];
  tiers: ModelGovernanceTier[];
}

/** Read-before-write tier identifiers (spec 0004 §2.5). */
export type RiskTierId = 'T0' | 'T1' | 'T2' | 'T3';

/** One read-before-write risk tier (spec 0004 §2.5). */
export interface RiskTier {
  tier: RiskTierId;
  /** What this tier means / example actions. */
  description: string;
  /** The approval this tier requires. */
  approval: string;
}

/** 200 from GET /admin/risk-tiers — the risk-tier reference (T0–T3). */
export interface RiskTierList {
  items: RiskTier[];
}

// --- Sources (contracts/openapi.yaml §sources, ADR-0009 / #108) ---

/**
 * The connector kind. `web` is the first connector (ADR-0009 §2): paste a public
 * URL, we ingest it — zero source-side setup. Future connectors add their own
 * values here, each behind its own ADR.
 */
export type SourceType = 'web';

/**
 * How a `web` source's URL is interpreted (ADR-0009 §2). `page` = one URL → one
 * document; `feed` = an RSS/Atom feed → many; `sitemap` = a sitemap.xml → many.
 * The server detects the mode from the fetched content.
 */
export type WebSourceMode = 'page' | 'feed' | 'sitemap';

/**
 * Sync lifecycle for the connector health grid (ADR-0009 §4). `pending` = added,
 * not yet synced; `syncing` = a sync is in flight; `ready` = last sync succeeded;
 * `error` = the last sync failed (see `last_error`).
 */
export type SourceStatus = 'pending' | 'syncing' | 'ready' | 'error';

/** Connector configuration. For the `web` connector: the fetched url + detected mode. */
export interface SourceConfig {
  /** The public URL this source ingests (http/https only; SSRF-checked). */
  url: string;
  mode: WebSourceMode;
}

/**
 * One connected source, tenant- and owner-scoped (ADR-0009 §4/§5, spec 0004
 * INV-1/INV-2). Ingested content is retrievable only by the owner within tenant.
 */
export interface Source {
  id: string;
  type: SourceType;
  config: SourceConfig;
  status: SourceStatus;
  /** Documents this source has ingested (0 until the first sync completes). */
  indexed_count: number;
  /** When the last successful sync finished (null before the first sync). */
  last_synced_at?: string | null;
  /** Failure reason when status is error. */
  last_error?: string;
  owner_id: string;
  created_at: string;
  updated_at: string;
}

/** 200 from GET /sources — a cursor page of sources. */
export interface SourceList {
  items: Source[];
  next_cursor?: string | null;
}

/**
 * POST /sources body. For the `web` connector: `{type: 'web', url}`. The server
 * validates + SSRF-checks the URL; an invalid or blocked URL → 422 (INV-8,
 * ADR-0009 §3).
 */
export interface SourceCreate {
  type: SourceType;
  /** The public URL to ingest (http/https only). */
  url: string;
}

// --- WebSocket envelopes (contracts/websocket-envelopes.schema.json) ---
// Lifecycle: start -> (delta | event)* -> done | error, exactly one terminal.
export type EnvelopeType = 'start' | 'delta' | 'event' | 'done' | 'error';

interface BaseEnvelope {
  type: EnvelopeType;
  /** Correlates all messages of one logical stream. */
  streamId: string;
  /** Monotonically increasing per streamId; defines ordering. */
  seq: number;
  /** Server send time (optional, ISO-8601). */
  ts?: string;
}

export interface StartEnvelope extends BaseEnvelope {
  type: 'start';
  /** Stream-open metadata; shape defined per feature. */
  data?: Record<string, unknown>;
}

export interface DeltaEnvelope extends BaseEnvelope {
  type: 'delta';
  /** Incremental output (e.g. a token chunk). Payload shape defined per feature. */
  data: unknown;
}

export interface EventEnvelope extends BaseEnvelope {
  type: 'event';
  /** Structured side-band event name (e.g. citation, tool_call). */
  name: string;
  data?: unknown;
}

export interface DoneEnvelope extends BaseEnvelope {
  type: 'done';
  /** Terminal success summary; shape defined per feature. */
  data?: Record<string, unknown>;
}

/** Subset of Problem carried on a WS error envelope (title + status required). */
export interface WsProblem {
  title: string;
  status: number;
  detail?: string;
  code?: string;
}

export interface ErrorEnvelope extends BaseEnvelope {
  type: 'error';
  problem: WsProblem;
}

export type WsEnvelope =
  | StartEnvelope
  | DeltaEnvelope
  | EventEnvelope
  | DoneEnvelope
  | ErrorEnvelope;

/** A terminal envelope ends a stream (exactly one per streamId). */
export type TerminalEnvelope = DoneEnvelope | ErrorEnvelope;

// --- Chat answer-stream payloads (websocket-envelopes.schema.json x-chatStream) ---
// These slot into the generic envelope `data`/`event` shapes for a chat answer:
//   start(ChatStartData) -> ( delta(ChatTokenDelta) | event:tool_call(ChatToolCall)
//     | event:tool_result(ChatToolResult) | event:citation(ChatCitation) )*
//   -> done(ChatDoneData) | error(Problem)

/** `start.data` for a chat answer stream. */
export interface ChatStartData {
  sessionId: string;
  /** Id the in-progress assistant message will be persisted under. */
  messageId: string;
  /** Model id producing this answer. */
  model: string;
}

/** `delta.data` — one streamed chunk of the assistant answer. */
export interface ChatTokenDelta {
  text: string;
}

/**
 * `event.data` for name=citation. Mirrors the REST Citation (spec 0004 INV-3) but
 * camelCased per the WS envelope schema. Rendered as a clickable reference
 * resolving to the document + span.
 */
export interface ChatCitation {
  id: string;
  documentId: string;
  documentName: string;
  chunkId: string;
  snippet: string;
  charStart: number;
  charEnd: number;
  score?: number;
}

/** Retrieval tool the chat agent can invoke (surfaced for "searching…" UX). */
export type ChatTool = 'search_text' | 'search_documents' | 'get_document';

/** `event.data` for name=tool_call — the agent invoked a retrieval tool. */
export interface ChatToolCall {
  callId: string;
  tool: ChatTool;
  args: Record<string, unknown>;
}

/** `event.data` for name=tool_result — outcome of a tool_call. */
export interface ChatToolResult {
  callId: string;
  tool: ChatTool;
  hitCount: number;
  summary?: string;
}

/** `done.data` — terminal success summary for a chat answer. */
export interface ChatDoneData {
  messageId: string;
  /** e.g. stop, length, content_filter. */
  finishReason: string;
  citationCount: number;
  usage?: {
    promptTokens?: number;
    completionTokens?: number;
    totalTokens?: number;
  };
}

// --- Preferences / saved searches / suggestions (spec 0005, epic #144) ------

/** `GET`/`PATCH /preferences` response — the caller's account preferences. */
export interface UserPreferences {
  /** A `/models` id, or null to use the server default. */
  default_model_id: string | null;
  /** When last changed, or null if never (the implicit server-default state). */
  updated_at: string | null;
}

/** `PATCH /preferences` body — partial (at least one field). */
export interface UserPreferencesUpdate {
  /** A `/models` id to set, or null to clear (fall back to the server default). */
  default_model_id?: string | null;
}

/** A saved `/search` query + its filters. */
export interface SavedSearch {
  id: string;
  name: string;
  query: string;
  collection_id?: string | null;
  source?: ResultSource | null;
  type?: string | null;
  owner_id: string;
  created_at: string;
  updated_at: string;
}

/** `POST /saved-searches` body. */
export interface SavedSearchCreate {
  name: string;
  query: string;
  collection_id?: string;
  source?: ResultSource;
  type?: string;
}

/** `PATCH /saved-searches/{id}` body — partial (at least one field). */
export interface SavedSearchUpdate {
  name?: string;
  query?: string;
  collection_id?: string | null;
  source?: ResultSource | null;
  type?: string | null;
}

/** `GET /saved-searches` response (cursor-paginated). */
export interface SavedSearchList {
  items: SavedSearch[];
  next_cursor?: string | null;
}

/** What a typeahead suggestion represents. */
export type SuggestionKind = 'completion' | 'document' | 'saved_search';

/** One typeahead suggestion from `GET /search/suggest`. */
export interface Suggestion {
  kind: SuggestionKind;
  text: string;
  document_id?: string | null;
  source?: ResultSource | null;
  saved_search_id?: string | null;
}

/** `GET /search/suggest` response. */
export interface SuggestResponse {
  suggestions: Suggestion[];
}

/** One recent `/search` query the caller ran. */
export interface RecentSearch {
  query: string;
  last_used_at: string;
}

/** `GET /search/recent` response. */
export interface RecentSearchList {
  items: RecentSearch[];
}
