/**
 * Hand-authored mirror of the frozen wire contract.
 *
 * SOURCE OF TRUTH: `contracts/openapi.yaml` and
 * `contracts/websocket-envelopes.schema.json`. The canonical TypeScript for the
 * REST surface is GENERATED by `pnpm gen:api` into `src/api/generated/schema.ts`
 * (gitignored). These hand-authored types exist so the app type-checks BEFORE
 * `gen:api` has been run (the generated dir is not committed). When the two
 * disagree, the generated output — i.e. the contract — wins; update this file or
 * (better) re-export from the generated types.
 */

// --- REST: GET /health (HealthStatus) ---
export interface HealthStatus {
  status: 'ok';
  service: string;
  version: string;
}

// --- REST: GET /health/ready (ReadinessStatus) ---
export type ReadinessState = 'ready' | 'degraded';

export interface DependencyStatus {
  /** Dependency identifier (e.g. postgres, redis, minio). */
  name: string;
  ok: boolean;
  /** Optional human-readable detail when not ok. */
  detail?: string;
}

export interface ReadinessStatus {
  status: ReadinessState;
  dependencies: DependencyStatus[];
}

// --- Auth (contracts/openapi.yaml §auth, spec 0004 §2.3) ---

/** POST /auth/login body. `password` is write-only on the wire. */
export interface LoginRequest {
  email: string;
  password: string;
}

/** 200 from POST /auth/login and POST /auth/refresh. */
export interface TokenResponse {
  /** Short-lived JWT bearer token. */
  access_token: string;
  token_type: 'bearer';
  /** Access-token lifetime in seconds. */
  expires_in: number;
}

/** Tenant roles (MVP RBAC, spec 0004 §2.3). */
export type UserRole = 'member' | 'admin' | 'security';

/** 200 from GET /auth/me — the authenticated principal. */
export interface CurrentUser {
  id: string;
  email: string;
  /** Resolved from the bearer token; clients never send it (spec 0004). */
  tenant_id: string;
  roles: UserRole[];
  created_at: string;
}

// --- Collections (contracts/openapi.yaml §collections) ---

/** POST /collections body. */
export interface CollectionCreate {
  name: string;
  description?: string;
}

/** PATCH /collections/{id} body — at least one property required (minProperties: 1). */
export interface CollectionUpdate {
  name?: string;
  description?: string;
}

/** A collection (folder grouping documents). */
export interface Collection {
  id: string;
  name: string;
  description?: string;
  owner_id: string;
  document_count: number;
  created_at: string;
  updated_at: string;
}

/** 200 from GET /collections — a cursor page of collections. */
export interface CollectionList {
  items: Collection[];
  /** Cursor for the next page, or null when exhausted. */
  next_cursor?: string | null;
}

// --- Documents (contracts/openapi.yaml §documents) ---

/** Ingestion lifecycle (parse → chunk → embed). */
export type DocumentStatus = 'pending' | 'processing' | 'ready' | 'failed';

/** A document's metadata, including its ingestion status. */
export interface Document {
  id: string;
  filename: string;
  mime_type: string;
  size_bytes: number;
  collection_id: string;
  owner_id: string;
  status: DocumentStatus;
  /** Failure reason when status is failed. */
  error?: string;
  /** Number of indexed chunks (0 until ingestion completes). */
  chunk_count: number;
  created_at: string;
  updated_at: string;
}

/** 200 from GET /documents — a cursor page of documents. */
export interface DocumentList {
  items: Document[];
  next_cursor?: string | null;
}

/** Query filters for GET /documents (collection / status / filename substring). */
export interface DocumentListQuery {
  collection_id?: string;
  status?: DocumentStatus;
  /** Filename substring (lexical, not semantic). */
  q?: string;
  cursor?: string;
  limit?: number;
}

// --- Shared error model: Problem (RFC-9457 application/problem+json) ---
export interface ProblemFieldError {
  field: string;
  message: string;
}

export interface Problem {
  /** URI identifying the problem type. Defaults to "about:blank". */
  type: string;
  /** Short, human-readable summary. */
  title: string;
  /** HTTP status code. */
  status: number;
  /** Human-readable explanation for this occurrence. */
  detail?: string;
  instance?: string;
  /** Stable, machine-readable error code for clients to branch on. */
  code?: string;
  /** Field-level validation errors, when applicable. */
  errors?: ProblemFieldError[];
}

// --- WebSocket envelopes (contracts/websocket-envelopes.schema.json) ---
// Lifecycle: start -> (delta | event)* -> done | error, exactly one terminal.
export type EnvelopeType = 'start' | 'delta' | 'event' | 'done' | 'error';

interface BaseEnvelope {
  type: EnvelopeType;
  /** Correlates all messages of one logical stream. */
  streamId: string;
  /** Monotonically increasing per streamId; defines ordering. */
  seq: number;
  /** Server send time (optional, ISO-8601). */
  ts?: string;
}

export interface StartEnvelope extends BaseEnvelope {
  type: 'start';
  /** Stream-open metadata; shape defined per feature. */
  data?: Record<string, unknown>;
}

export interface DeltaEnvelope extends BaseEnvelope {
  type: 'delta';
  /** Incremental output (e.g. a token chunk). Payload shape defined per feature. */
  data: unknown;
}

export interface EventEnvelope extends BaseEnvelope {
  type: 'event';
  /** Structured side-band event name (e.g. citation, tool_call). */
  name: string;
  data?: unknown;
}

export interface DoneEnvelope extends BaseEnvelope {
  type: 'done';
  /** Terminal success summary; shape defined per feature. */
  data?: Record<string, unknown>;
}

/** Subset of Problem carried on a WS error envelope (title + status required). */
export interface WsProblem {
  title: string;
  status: number;
  detail?: string;
  code?: string;
}

export interface ErrorEnvelope extends BaseEnvelope {
  type: 'error';
  problem: WsProblem;
}

export type WsEnvelope =
  | StartEnvelope
  | DeltaEnvelope
  | EventEnvelope
  | DoneEnvelope
  | ErrorEnvelope;

/** A terminal envelope ends a stream (exactly one per streamId). */
export type TerminalEnvelope = DoneEnvelope | ErrorEnvelope;
