"""mvp relational schema — tenant/owner-scoped tables (#44)

Creates the grounded-chat MVP schema on top of the pgvector extension (0001):
``tenants``, ``users``, ``collections``, ``documents``, ``chunks`` (with the
in-row ``vector(1024)`` embedding), ``chat_sessions``, ``messages``,
``citations``, and the append-only ``audit_events``. Shapes per spec 0004 §4 and
the frozen contract schemas; hand-written (not autogenerated) and reversible.

Tenancy/ownership invariants baked in (spec 0004 §2.1/§2.2):

* every tenant-scoped table has a non-null, indexed ``tenant_id`` FK → ``tenants``
  (the INV-1 predicate column + the RLS-backstop key);
* ``collections``/``documents``/``chat_sessions`` carry an indexed ``owner_id``;
* ``chunks.embedding`` is ``vector(1024)`` (``LLM_EMBEDDING_DIMENSIONS``) in-row;
* ``audit_events`` is append-only: this migration **revokes UPDATE/DELETE** from
  the application DB role (spec 0004 §2.4 tamper-evidence). The per-event
  hash-chain is a follow-up (``revisit-at-implementation``). RLS policies are a
  separate follow-up migration (spec 0004 §2.1), explicitly OUT of #44.

Embedding dimension is pinned as a literal here (a migration is an immutable
snapshot): it must equal ``Settings.llm_embedding_dimensions`` (1024). Changing
the embedding model is a new migration, not an edit to this one.

Revision ID: 0002_mvp_schema
Revises: 0001_enable_pgvector
Create Date: 2026-06-18 18:55:00+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002_mvp_schema"
down_revision: str | None = "0001_enable_pgvector"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Pinned width of the chunk embedding (LLM_EMBEDDING_DIMENSIONS). See module docstring.
_EMBEDDING_DIM = 1024


def _ts_columns() -> tuple[sa.Column[object], sa.Column[object]]:
    """``created_at`` / ``updated_at``, server-defaulted UTC (matches the ORM)."""
    return (
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )


def upgrade() -> None:
    # --- tenants (the isolation root) ---------------------------------------
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        *_ts_columns(),
    )

    # --- users (one tenant each; email unique within tenant) ----------------
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("roles", postgresql.ARRAY(sa.Text()), nullable=False),
        *_ts_columns(),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_email"),
    )
    op.create_index("ix_users_tenant_id", "users", ["tenant_id"])

    # --- collections (ownership-bearing) ------------------------------------
    op.create_table(
        "collections",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "owner_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        *_ts_columns(),
    )
    op.create_index("ix_collections_tenant_id", "collections", ["tenant_id"])
    op.create_index("ix_collections_owner_id", "collections", ["owner_id"])

    # --- documents (ownership-bearing) --------------------------------------
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "owner_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "collection_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("collections.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        *_ts_columns(),
        sa.CheckConstraint("size_bytes >= 0", name="ck_documents_size_nonneg"),
    )
    op.create_index("ix_documents_tenant_id", "documents", ["tenant_id"])
    op.create_index("ix_documents_owner_id", "documents", ["owner_id"])
    op.create_index("ix_documents_collection_id", "documents", ["collection_id"])

    # --- chunks (embedding in-row beside tenant_id + document_id) -----------
    op.create_table(
        "chunks",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "document_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("documents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(_EMBEDDING_DIM), nullable=True),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        *_ts_columns(),
        sa.UniqueConstraint("document_id", "ord", name="uq_chunks_document_ord"),
        sa.CheckConstraint("char_start >= 0", name="ck_chunks_char_start_nonneg"),
        sa.CheckConstraint("char_end >= char_start", name="ck_chunks_char_span"),
    )
    op.create_index("ix_chunks_tenant_id", "chunks", ["tenant_id"])
    op.create_index("ix_chunks_document_id", "chunks", ["document_id"])

    # --- chat_sessions (ownership-bearing) ----------------------------------
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "owner_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        *_ts_columns(),
    )
    op.create_index("ix_chat_sessions_tenant_id", "chat_sessions", ["tenant_id"])
    op.create_index("ix_chat_sessions_owner_id", "chat_sessions", ["owner_id"])

    # --- messages -----------------------------------------------------------
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "session_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("chat_sessions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=True),
        *_ts_columns(),
    )
    op.create_index("ix_messages_tenant_id", "messages", ["tenant_id"])
    op.create_index("ix_messages_session_id", "messages", ["session_id"])

    # --- citations ----------------------------------------------------------
    op.create_table(
        "citations",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "message_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("messages.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "chunk_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("chunks.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        *_ts_columns(),
        sa.CheckConstraint("char_start >= 0", name="ck_citations_char_start_nonneg"),
        sa.CheckConstraint("char_end >= char_start", name="ck_citations_char_span"),
    )
    op.create_index("ix_citations_tenant_id", "citations", ["tenant_id"])
    op.create_index("ix_citations_message_id", "citations", ["message_id"])
    op.create_index("ix_citations_chunk_id", "citations", ["chunk_id"])

    # --- audit_events (append-only; UPDATE/DELETE revoked below) ------------
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "ts",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "actor_id",
            sa.Uuid(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.Column("source_ip", postgresql.INET(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(), nullable=False),
    )
    op.create_index("ix_audit_events_tenant_id", "audit_events", ["tenant_id"])
    op.create_index("ix_audit_events_tenant_ts", "audit_events", ["tenant_id", "ts"])
    op.create_index("ix_audit_events_actor_id", "audit_events", ["actor_id"])

    # Tamper-evidence (spec 0004 §2.4): the application DB role must hold no
    # UPDATE/DELETE on the audit log. We revoke from the *current* role (the role
    # that runs the app's migrations and queries with the app DSN). If/when a
    # dedicated least-privilege app role lands, this revoke targets that role.
    op.execute("REVOKE UPDATE, DELETE ON TABLE audit_events FROM CURRENT_USER")


def downgrade() -> None:
    # Re-grant before dropping so the revoke does not strand a managed role, then
    # drop children → parents (reverse FK order). Indexes drop with their tables.
    op.execute("GRANT UPDATE, DELETE ON TABLE audit_events TO CURRENT_USER")
    op.drop_table("audit_events")
    op.drop_table("citations")
    op.drop_table("messages")
    op.drop_table("chat_sessions")
    op.drop_table("chunks")
    op.drop_table("documents")
    op.drop_table("collections")
    op.drop_table("users")
    op.drop_table("tenants")
