[package]
name = "lumen-docintel-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "lumen_docintel"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json.workspace = true
lumen-docintel = { path = "../lumen-docintel", version = "=0.1.0" }
pyo3.workspace = true
