"""CI release-wheel check using only installed wheel assets and generated bytes."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import lumen_docintel

if "--limited-child" not in sys.argv:
    subprocess.run(
        [sys.executable, __file__, "--limited-child"], check=True, timeout=30
    )
    raise SystemExit(0)

project = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(project / "backend" if (project / "backend").is_dir() else project))
from app.ingestion._pdf_worker import apply_memory_limit  # noqa: E402

if sys.platform != "darwin":
    apply_memory_limit(256 * 1024 * 1024)
else:
    # Artifact verification only: generated bytes, parent deadline. The runtime
    # refuses macOS before accepting untrusted input until a hard cap is available.
    try:
        apply_memory_limit(256 * 1024 * 1024)
    except OSError:
        pass
    else:
        raise AssertionError("macOS runtime must fail closed")

root = Path(lumen_docintel.__file__).parent / "pdfium"
pin = json.loads((root / "pin.json").read_text(encoding="utf-8"))
assert pin["release"] == "chromium/7881"
assert (root / "licenses/pdfium.txt").is_file()
assert (root / "licenses/freetype.txt").is_file()
assert (root / "LICENSE").is_file()
values = [
    b"<< /Type /Catalog /Pages 2 0 R >>",
    b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] >>",
]
data = bytearray(b"%PDF-1.7\n")
offsets = []
for index, value in enumerate(values, 1):
    offsets.append(len(data))
    data.extend(f"{index} 0 obj\n".encode() + value + b"\nendobj\n")
xref = len(data)
data.extend(b"xref\n0 4\n0000000000 65535 f \n")
for offset in offsets:
    data.extend(f"{offset:010} 00000 n \n".encode())
data.extend(f"trailer\n<< /Root 1 0 R /Size 4 >>\nstartxref\n{xref}\n%%EOF\n".encode())
# This script is itself a throwaway isolated CI process. Runtime facade tests
# separately prove the OS-limit handshake and cancellation supervision.
result = json.loads(
    lumen_docintel._extract_pdfium_worker(bytes(data), str(root / pin["library"]), "{}")
)
assert result["document"]["generation"]["outcome"] == "needs_ocr"
assert result["document"]["generation"]["parser_id"] == "rust-pdfium"
print(
    "Installed release wheel: PDFium loads; notices present; generated scan is needs_ocr"
)
